import type { Metadata } from 'next'
import './globals.css'
import { exo_2, heebo } from './fonts'
import Sidebar from './components/Sidebar'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${exo_2.variable} ${heebo.variable}`}>
      
      <body className='flex grid grid-cols-layout grid-rows-layout'>
        <Sidebar />
        {children}
        <Footer />
      </body>
    </html>
  )
}

